# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c10b8a57186a5ebd5606e3e5a4ca9d7d07ca60a4939c77c5593eca324008c3020291274bd19b0ad0d02c2a493a61ce903668e1df071ee217e41b9901ef8431c1

test:
  secret_key_base: af986620979de47189649ee7c78956b1de7fcf74d2fd287ceffe6ccee1264d71a0b5571ab8c769fa41d847b24e7921ec1f7f3943db5829ac1c3eb211745e0edb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
